spring:
  application:
    name: spring-boot-rabbitmq
  rabbitmq:
    host: 192.168.1.100
    port: 5672
    username: guest
    password: guest

  redis:
    database: 0
    password:
    host: 192.168.1.100
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 1

